apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: drone-detector-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
      - image: europe-north2-docker.pkg.dev/drone-detection-mlops/ml-containers/api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: '2'
        env:
        - name: MODE
          value: cloud
  traffic:
  - percent: 100
    latestRevision: true
